name: 'Build Project'

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  BuildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build e Publish Artifact
  jobs:

  - job: build
    displayName: 'Build Job'
    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: 'src/FIAP.FCG.API/FIAP.FCG.API.csproj' 

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: 'src/FIAP.FCG.API/FIAP.FCG.API.csproj'
        arguments: '-c $(BuildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        projects: 'src/FIAP.FCG.API/FIAP.FCG.API.csproj'
        arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/$(BuildConfiguration) --no-build'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
      

